### ISSUE TITLE
Watermark feature broken?

### ISSUE THREAD

**Issue by richardbarran** [jdriscoll/django-photologue#108]
On django-phototologue.net website: seems to break whenever you add a watermark, e.g.:

```
Internal Server Error: /admin/photologue/watermark/add/
Traceback (most recent call last):
 File "/home/webby/.virtualenvs/photologue_website/lib/python3.3/site-packages/django/core/handlers/base.py", line 111, in get_response
   response = wrapped_callback(request, *callback_args, **callback_kwargs)
 File "/home/webby/.virtualenvs/photologue_website/lib/python3.3/site-packages/django/contrib/admin/options.py", line 567, in wrapper
   return self.admin_site.admin_view(view)(*args, **kwargs)
 File "/home/webby/.virtualenvs/photologue_website/lib/python3.3/site-packages/django/utils/decorators.py", line 105, in _wrapped_view
   response = view_func(request, *args, **kwargs)
 File "/home/webby/.virtualenvs/photologue_website/lib/python3.3/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
   response = view_func(request, *args, **kwargs)
 File "/home/webby/.virtualenvs/photologue_website/lib/python3.3/site-packages/django/contrib/admin/sites.py", line 204, in inner
   return view(request, *args, **kwargs)
 File "/home/webby/.virtualenvs/photologue_website/lib/python3.3/site-packages/django/contrib/admin/options.py", line 1437, in add_view
   return self.changeform_view(request, None, form_url, extra_context)
 File "/home/webby/.virtualenvs/photologue_website/lib/python3.3/site-packages/django/utils/decorators.py", line 29, in _wrapper
   return bound_func(*args, **kwargs)
 File "/home/webby/.virtualenvs/photologue_website/lib/python3.3/site-packages/django/utils/decorators.py", line 105, in _wrapped_view
   response = view_func(request, *args, **kwargs)
 File "/home/webby/.virtualenvs/photologue_website/lib/python3.3/site-packages/django/utils/decorators.py", line 25, in bound_func
   return func.__get__(self, type(self))(*args2, **kwargs2)
 File "/home/webby/.virtualenvs/photologue_website/lib/python3.3/site-packages/django/db/transaction.py", line 394, in inner
   return func(*args, **kwargs)
 File "/home/webby/.virtualenvs/photologue_website/lib/python3.3/site-packages/django/contrib/admin/options.py", line 1388, in changeform_view
   self.save_model(request, new_object, form, not add)
 File "/home/webby/.virtualenvs/photologue_website/lib/python3.3/site-packages/django/contrib/admin/options.py", line 1029, in save_model
   obj.save()
 File "/home/webby/.virtualenvs/photologue_website/lib/python3.3/site-packages/photologue/models.py", line 782, in save
   self.create_sample()
 File "/home/webby/.virtualenvs/photologue_website/lib/python3.3/site-packages/photologue/models.py", line 751, in create_sample
   im = self.process(im)
 File "/home/webby/.virtualenvs/photologue_website/lib/python3.3/site-packages/photologue/models.py", line 770, in process
   im = self.post_process(im)
 File "/home/webby/.virtualenvs/photologue_website/lib/python3.3/site-packages/photologue/models.py", line 886, in post_process
   return apply_watermark(im, mark, self.style, self.opacity)
 File "/home/webby/.virtualenvs/photologue_website/lib/python3.3/site-packages/photologue/utils/watermark.py", line 50, in apply_watermark
   layer.paste(mark, ((im.size[0] - w) / 2, (im.size[1] - h) / 2))
 File "/home/webby/.virtualenvs/photologue_website/lib/python3.3/site-packages/PIL/Image.py", line 1316, in paste
   self.im.paste(im, box)
TypeError: integer argument expected, got float

Request repr(): 
<WSGIRequest
path:/admin/photologue/watermark/add/,
GET:<QueryDict: {}>,
POST:{'_continue': 'Save and continue editing',
'csrfmiddlewaretoken': 'R8KCdobkfskDiXtD4yNNvYfHV8Zq4Z2a',
'description': '',
'name': 'Test',
'opacity': '50',
'style': 'scale'},
COOKIES:{'_ga': 'GA1.2.1826507311.1409774054',
'_gat': '1',
'csrftoken': 'R8KCdobkfskDiXtD4yNNvYfHV8Zq4Z2a',
'sessionid': 'o4rt9gtzxx6vwlcj761y0s8rph81wb85'},
META:{'CONTENT_LENGTH': '262724',
'CONTENT_TYPE': 'multipart/form-data; boundary=----WebKitFormBoundaryc7ejvN4AAoe3I8mF',
'CSRF_COOKIE': 'R8KCdobkfskDiXtD4yNNvYfHV8Zq4Z2a',
'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
'HTTP_ACCEPT_ENCODING': 'gzip,deflate',
'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.8,zh-CN;q=0.6,zh;q=0.4',
'HTTP_CACHE_CONTROL': 'max-age=0',
'HTTP_CONNECTION': 'close',
'HTTP_COOKIE': '_gat=1; sessionid=o4rt9gtzxx6vwlcj761y0s8rph81wb85; csrftoken=R8KCdobkfskDiXtD4yNNvYfHV8Zq4Z2a; _ga=GA1.2.1826507311.1409774054',
'HTTP_HOST': 'www.django-photologue.net',
'HTTP_ORIGIN': 'http://www.django-photologue.net',
'HTTP_REFERER': 'http://www.django-photologue.net/admin/photologue/watermark/add/',
'HTTP_USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.122 Safari/537.36',
'HTTP_X_FORWARDED_FOR': '82.69.66.125',
'HTTP_X_REAL_IP': '82.69.66.125',
'HTTP_X_SCHEME': 'http',
'PATH_INFO': '/admin/photologue/watermark/add/',
'QUERY_STRING': '',
'RAW_URI': '/admin/photologue/watermark/add/',
'REMOTE_ADDR': '82.69.66.125',
'REMOTE_PORT': '80',
'REQUEST_METHOD': 'POST',
'SCRIPT_NAME': '',
'SERVER_NAME': 'www.django-photologue.net',
'SERVER_PORT': '80',
'SERVER_PROTOCOL': 'HTTP/1.0',
'SERVER_SOFTWARE': 'gunicorn/18.0',
'gunicorn.socket': <socket.socket object, fd=14, family=2, type=1, proto=0>,
'wsgi.errors': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='ANSI_X3.4-1968'>,
'wsgi.file_wrapper': <class 'gunicorn.http.wsgi.FileWrapper'>,
'wsgi.input': <gunicorn.http.body.Body object at 0x7f6f0aacfbd0>,
'wsgi.multiprocess': True,
'wsgi.multithread': False,
'wsgi.run_once': False,
'wsgi.url_scheme': 'http',
'wsgi.version': (1, 0)}>
```

**Comment by hambro** [comment]
I'm no expert, but try editing line 52 in django-photologue/photologue/utils/watermark.py to this:
layer.paste(mark, (round((im.size[0] - w) / 2), round((im.size[1] - h) / 2)))

**Comment by richardbarran** [comment]
Thank you for the suggestion - that fixed the issue!
