### ISSUE TITLE
Initial Migration fails on Django 1.7.4 & Python 2.7

### ISSUE THREAD

**Issue by web-snake** [jdriscoll/django-photologue#125]
I followed the install directions on Read the Docs and I'm pretty sure I did that right.
When I do the initial:
$ python manage.py migrate photologue
I get the following error:
  Applying photologue.0001_initial...Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/root/.virtualenvs/photolouge_test/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/root/.virtualenvs/photolouge_test/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/.virtualenvs/photolouge_test/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/root/.virtualenvs/photolouge_test/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/root/.virtualenvs/photolouge_test/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 161, in handle
    executor.migrate(targets, plan, fake=options.get("fake", False))
  File "/root/.virtualenvs/photolouge_test/lib/python2.7/site-packages/django/db/migrations/executor.py", line 68, in migrate
    self.apply_migration(migration, fake=fake)
  File "/root/.virtualenvs/photolouge_test/lib/python2.7/site-packages/django/db/migrations/executor.py", line 102, in apply_migration
    migration.apply(project_state, schema_editor)
  File "/root/.virtualenvs/photolouge_test/lib/python2.7/site-packages/django/db/migrations/migration.py", line 108, in apply
    operation.database_forwards(self.app_label, schema_editor, project_state, new_state)
  File "/root/.virtualenvs/photolouge_test/lib/python2.7/site-packages/django/db/migrations/operations/fields.py", line 37, in database_forwards
    field,
  File "/root/.virtualenvs/photolouge_test/lib/python2.7/site-packages/django/db/backends/sqlite3/schema.py", line 176, in add_field
    self._remake_table(model, create_fields=[field])
  File "/root/.virtualenvs/photolouge_test/lib/python2.7/site-packages/django/db/backends/sqlite3/schema.py", line 144, in _remake_table
    self.quote_name(model._meta.db_table),
  File "/root/.virtualenvs/photolouge_test/lib/python2.7/site-packages/django/db/backends/schema.py", line 102, in execute
    cursor.execute(sql, params)
  File "/root/.virtualenvs/photolouge_test/lib/python2.7/site-packages/django/db/backends/utils.py", line 81, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/root/.virtualenvs/photolouge_test/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/root/.virtualenvs/photolouge_test/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/root/.virtualenvs/photolouge_test/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/root/.virtualenvs/photolouge_test/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 485, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: table photologue_gallery__new has no column named photos

This appears ( to me ) to be a problem with the models or migrations or the DB layer
As you can see I'm just using SQLite right now. Is that going to cause a problem?
I didn't see anything in the docs suggesting that was a problem.
I am also using Django 1.7.4
I noticed your latest Travis tests are using 1.7.2
Do you think this could have anything to do with this error?
I am fairly new to using Django 1.7 so I'm not super familiar with the new built in migrations and what can go wrong there and what kinds of errors might be thrown, but the directions are pretty simple and I followed them.
I'm at a loss to what could cause this kind of error, I imagine your models themselves  are pretty stable  by now so it must be something to do with how they are being introduced to the fresh DB.

**Comment by web-snake** [comment]
Its seems like there were two problems I ran into working from the docs:
What I think the problem was is that in the docs you mention that using Django <1.7 you need to include the South Migrations setting:
SOUTH_MIGRATION_MODULES = {
    'photologue': 'photologue.south_migrations',
}
It seemed to imply that you don't need that setting if you're running Django 1.7.x
The error above I got while migrating went away when I included this setting:
MIGRATION_MODULES = {
    'photologue': 'photologue.south_migrations',
}
Perhaps I was supposed to know that's how it worked but if so the docs where written in a confusing way to people who are new to Django 1.7,
I'm assuming this setting is necessary, it seemed to solve my problem.
If so maybe its worth mentioning in the docs.
Also, probably unrelated,
I needed to include 'django.contrib.sites' in INSTALLED_APPS
because photolouge seemed to be dependant on it.
This was not listed in the docs under the required INSTALLED_APPS

**Comment by richardbarran** [comment]
Hi @web-snake - I've checked and there is an issue with Django 1.7.4; I will investigate this and the other issues that you have raised. Thanks for the report!

**Comment by richardbarran** [comment]
Django-photologue depends on django-sortedm2m, which has been broken by Django 1.7.4. See gregmuellegger/django-sortedm2m#43.
When sortedm2m fixes this and releases a new version, I will prepare a new release of Photologue that uses the fixed sortedm2m.

**For now** - the workaround is to use Django 1.7.3.

**Comment by richardbarran** [comment]
@web-snake: In ``MIGRATION_MODULES`` you should not be pointing to the old South-compatible migrations - I'm not sure why it worked for you! You shouldn't have to configure anything in Django 1.7.x.

Also, I've made a few changes to the documentation; hopefully it's a little bit clearer, but feedback is always welcome!

**Comment by richardbarran** [comment]
The next release of Photologue will install the latest version of django-sortedm2m, which should fix this migrations issue.
I'll close this issue, but please do not hesitate to re-open it if the problem reoccurs.
