### ISSUE TITLE
no photos added to cache Django 1.10, Photologue 3.6. Pillow 4.0

### ISSUE THREAD

**Issue by professorDante** [jdriscoll/django-photologue#171]
I cannot get any photos to be added to the cache at all. All the photo sizes have been made. Photo uploads, but just get no images at all. Checking the cache directory shows no photos added.

**Comment by professorDante** [comment]
Also, running plcache produces this stack trace:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/boardwalk/webapps/boardwalk/lib/python2.7/Django-1.10.5-py2.7.egg/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/boardwalk/webapps/boardwalk/lib/python2.7/Django-1.10.5-py2.7.egg/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/boardwalk/webapps/boardwalk/lib/python2.7/Django-1.10.5-py2.7.egg/django/core/management/__init__.py", line 208, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/home/boardwalk/webapps/boardwalk/lib/python2.7/Django-1.10.5-py2.7.egg/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/boardwalk/webapps/boardwalk/lib/python2.7/photologue/management/commands/plcache.py", line 7, in <module>
    class Command(BaseCommand):
  File "/home/boardwalk/webapps/boardwalk/lib/python2.7/photologue/management/commands/plcache.py", line 8, in Command
    option_list = BaseCommand.option_list + (
AttributeError: type object 'BaseCommand' has no attribute 'option_list'

**Comment by richardbarran** [comment]
Hi,
This issue has been fixed in [this commit](https://github.com/jdriscoll/django-photologue/commit/fd4bac9facd923d9aad4d99790db190be824c589) but I haven't got round to releasing a new version of Photologue yet.
If you install directly from Github, it will fix the issue.

**Comment by professorDante** [comment]
Howdy Richard,

Just to be clear - the no images being added to the cache has been fixed in tip?

**Comment by richardbarran** [comment]
Yes!

**Comment by professorDante** [comment]
Roger that - I'll give it a go!

**Comment by professorDante** [comment]
Running this command:

pip install git+ssh://git@github.com/jdriscoll/djangophotologue/commit/fd4bac9facd923d9aad4d99790db190be824c589

Gives me:

Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Are the permission OK on the commit?

**Comment by richardbarran** [comment]
How about 'git@github.com:jdriscoll/django-photologue.git' for the repo url?

**Comment by professorDante** [comment]
OK, this sort of works, as far as I can tell. 

1. Removed old photologue
2. pip install git+https://git@github.com/jdriscoll/django-photologue.git@fd4bac9facd923d9aad4d99790db190be824c589
3. Removed all photo sizes.
4. Add in admin_thumbnail size.
5. Upload image

Image still refuses to display thumbnail in admin. However, running:

python manage.py plcache

Then does correctly add the cached image admin thumbnail to the cache, and displays it. But why won't it do this automatically on upload?

**Comment by professorDante** [comment]
Now I'm repeatedly getting this error on running plcache:

  File "/home/boardwalk/lib/python2.7/photologue/models.py", line 456, in create_size
    raise e
io.UnsupportedOperation: fileno

**Comment by richardbarran** [comment]
Hi,
Could you provide a bit more information to help me with debugging this error:
- Full traceback.
- Python version
- Django version.

**Comment by professorDante** [comment]
traceback:

[boardwalk@web537 boardwalk]$ python2.7 manage.py plcache
Caching photos, this may take a while...
Cacheing admin_thumbnail size images
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/boardwalk/webapps/boardwalk/lib/python2.7/Django-1.10.5-py2.7.egg/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/boardwalk/webapps/boardwalk/lib/python2.7/Django-1.10.5-py2.7.egg/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/boardwalk/webapps/boardwalk/lib/python2.7/Django-1.10.5-py2.7.egg/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/boardwalk/webapps/boardwalk/lib/python2.7/Django-1.10.5-py2.7.egg/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/home/boardwalk/lib/python2.7/photologue/management/commands/plcache.py", line 40, in handle
    obj.create_size(photosize)
  File "/home/boardwalk/lib/python2.7/photologue/models.py", line 456, in create_size
    raise e
io.UnsupportedOperation: fileno

pip freeze:

[boardwalk@web537 boardwalk]$ pip freeze
chardet==2.2.1
Django==1.10.5
django-fack==1.1
django-photologue==3.7.dev0
django-recaptcha==1.2.1
django-sortedm2m==1.3.3
docopt==0.6.1
docutils==0.7
egenix-mx-base==3.1.3
ExifRead==2.1.2
iniparse==0.4
iotop==0.6
IPy==0.75
javapackages==1.0.0
kitchen==1.1.1
lxml==3.2.1
MySQL-python==1.2.3
netifaces==0.10.4
ngxtop==0.0.2
numpy==1.5.0
olefile==0.44
PIL==1.1.7
Pillow==4.0.0
policycoreutils-default-encoding==0.1
psycopg2==2.5.4
pycrypto==2.3
pycurl==7.19.0
pygpgme==0.3
pyliblzma==0.5.3
pyparsing==1.5.6
pyxattr==0.5.1
reportlab==2.4
seobject==0.1
sepolicy==1.1
tabulate==0.7.2
urlgrabber==3.10
yum-metadata-parser==1.1.4

**Comment by richardbarran** [comment]
Something's not quite right :) Looking at the end of the traceback:

    File "/home/boardwalk/lib/python2.7/photologue/models.py", line 456, in create_size
    raise e
    io.UnsupportedOperation: fileno

[But currently that code is line 439](https://github.com/jdriscoll/django-photologue/blob/master/photologue/models.py#L439).
It looks like the installation of the latest code from Github did not work; can you try again removing all downloaded Photologue code, and re-installing it?

**Comment by professorDante** [comment]
Howdy Rich,

I went back to the drawing board and installed it using python3 virtualenv, re-installed photologue, a nd everything works perfectly. It was something to do with PIL and pillow (again), and as Python3 doesn't use PIL, it worked.

**Comment by richardbarran** [comment]
👍
